import crypto from 'crypto';
import document from 'document';
import fs from 'fs';
import jpeg from 'jpeg';
import power from 'power';
import scientific from 'scientific';
import signal from 'scientific/signal';
import system from 'system';
import userActivity from 'user-activity';
import userSettings from 'user-settings';

console.log('typeof crypto: ' + typeof crypto);
console.log('typeof document: ' + typeof document);
console.log('typeof fs: ' + typeof fs);
console.log('typeof jpeg: ' + typeof jpeg);
console.log('typeof power: ' + typeof power);
console.log('typeof scientific: ' + typeof scientific);
console.log('typeof signal: ' + typeof signal);
console.log('typeof system: ' + typeof system);
console.log('typeof userActivity: ' + typeof userActivity);
console.log('typeof userSettings: ' + typeof userSettings);
