name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [10, 12]
    name: CI on NodeJS v${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Code style
        run: yarn lint |
             yarn checkstyle
      - name: Test
        run: yarn test:coveralls
