name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [12, 14, 16]
    name: ${{ matrix.os }} / Node v${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check code style (tsc + eslint)
        run: yarn lint
      - name: Check code style (Prettier)
        run: yarn checkstyle
      - name: Run tests
        run: yarn test --coverage
      - name: Upload coverage
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
